name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # Trigger workflow on push to main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Unit Tests
        run: mvn test

  deploy-to-jenkins:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Trigger Jenkins Job
        uses: appleboy/jenkins-action@v0.2.0
        with:
          url: ${{ secrets.JENKINS_URL }}
          user: ${{ secrets.JENKINS_USER }}
          token: ${{ secrets.JENKINS_API_TOKEN }}
          job: 'deploy-java-app' 
